### ISSUE TITLE
Question about default hole size

### ISSUE THREAD

**Issue by kalium99** [veikman/dactyl-keyboard#14]
Hi,

Before printing I spent time reading through the docs and the configs, but it seems that maybe I missed something. The cherry switches don't seem to fit the holes. The 'height' of the holes is not quite enough on the final product. Did I PEBKAC this (i.e didn't RTFM well enough) or is it potentially a printing issue?

Cheers

**Comment by veikman** [comment]
Hi,

The default switch type is ALPS-compatible. If you want holes for Cherry-style switches, you need a configuration file for it. Such a file is bundled with the application. Try this:

`lein run -c config/base.yaml -c config/dmote/base.yaml -c config/dmote/mx.yaml`

This is mentioned in [the intro](https://github.com/veikman/dactyl-keyboard/blob/master/doc/intro.md). I should probably make it more prominent, since most people do use MX.

If you’re already configuring for MX but the switches still don’t fit, please let me know. Good luck with your build.
