### ISSUE TITLE
Cannot remove aux0 cluster

### ISSUE THREAD

**Issue by ameyp** [veikman/dactyl-keyboard#23]
I'm trying to generate an SCAD file without the aux keys and the mounting plate, but deleting the aux0 sections from `dmote/base.yaml` make the compilation fail with `ExceptionInfo Configuration lacks key  clojure.core/ex-info (core.clj:4739)`

**Comment by veikman** [comment]
That happens because several other parts of `dmote/base.yaml` refer to the `aux0` cluster or its keys, `a0` and `a1`. In the following, I assume you’re using the current development snapshot, not a release version.

* `main-body` -> `bottom-plate` anchors a fastener to `a1`.
* `by-key` has settings for the `aux0` cluster.
* `tweaks` refers to  `a0` and `a1` in several places, integrating these keys with the rest of the keyboard case.

If you look at the details of the exception message, you can see what reference has been broken. If you remove them all, you get SCAD with a gap where the cluster used to be. Nothing about this process is peculiar to `aux0`.

**Comment by ameyp** [comment]
Ah, that's good to know! Also I didn't realize that it was an exception and that I could print the stack trace of that exception in the REPL, I assumed that it was just a println. Thanks!
