### ISSUE TITLE
DMOTE vs Dactyl Manuform? Thumbcluster adjustments? Back wall removal?

### ISSUE THREAD

**Issue by marcinliebiediew** [veikman/dactyl-keyboard#25]
Hi Viktor, thank you for your amazing work! This is not an issue.
I'm a happy owner of DMOTE, but I can no longer stand the wires and thanks to recent advancements in NRF+ProMicro community-designed circuits (https://github.com/joric/nrfmicro/releases/tag/1.3), I decided it would be shame to not use this as an opportunity to build myself another keyboard, but I can't decide which one to build. 

My questions:
1. have you ever printed dactyl manuform? if yes what's your opinion on it when compared with your work? I'm mainly interested in differences in how thumb keys are laid out. In DMOTE 3/7 keys seem to be hard to reach for me (mainly the middle one, the one behind it (looking from hand's perspective) and the one below them). On the other side, I feel like my thumb will be doing [this](https://media.giphy.com/media/3o6Zt0QxVmGWMjmpri/giphy.gif) on DManuform. Sorry for asking this non technical question - unfortunately, I didn't find any answers to that question online.
2. can you maybe point me a direction where in your config I could try to
  - adjust the angles of thumb cluster and it's placement relative to the rest of the case? I'd like to try:
    - rotate it towards ground, and in opposite direction
    - move it closer/away from the hand (`west`/`east` axis)
    - rotate it towards/outwards to the hand 

  - minimize the case: 
    - remove back wall (EDIT: cut down/slim down; just realized removal would suggest a hole in the case...) 
    - reduce/slim down amount of material connecting the case and cluster from the 'inside of the hand' (nearby south middle) - I'm ok with how challenging it will be to solder it

To some extent I got familiar with your config, I almost removed the back wall, but I always ended up with some artifacts like holes in case of hanging material.
Are these modifications possible to do from config, or do I have to dive into the code? (which is something I want to avoid since I'm not familiar with closure and it's ecosystem)

**Comment by veikman** [comment]
Hi, and thanks.

No, I haven’t printed a Dactyl-ManuForm. I don’t have trouble [reaching the thumb keys on a DMOTE](https://viktor.eikman.se/static/atcl/dmote020_thumb.webm), perhaps because my hands are on the large side.

For the position of the thumb cluster relative to its anchor, in the current draft towards version 0.6.0, you want to look at `anchoring` → `extrinsic-offset` for the `thumb0` cluster. For angles, the first place to look is `by-key` → `clusters` → `thumb0` → `parameters` → `layout`, where you will find base `roll` (x axis), `pitch` (y) and `yaw` (z). Because these three parameters are applied in sequence, they may behave counter to intuition, like a set of gimbals. Also note that the thumb cluster is actually composed of two clusters in the configuration; `thumb1` comprises the lowest two keys and may itself need rotation (or removal) for your design.

To get rid of the blocky far end of the case and replace it with a smaller wall, start by disabling `rear-housing` and the tweaks that target it, then enable `to-ground` for the `north` wall of the `main` cluster. A comparison with the Dactyl-ManuForm configuration file should be useful here, as it has no rear housing.

Good luck with the wireless build!

**Comment by veikman** [comment]
To make key-cluster rotation easier, I’ve shifted from doing it in `by-key` to doing it with standard anchoring (using `key-clusters`), in fa17f33acbdfceb9237f36cc974da9f01a9c9c83. Please let me know if you have further questions.
